### PR TITLE
Fixed Issue 71: Directory not found

### PR DESCRIPTION
**Pull request by toszter**
Based on 5b18aeeb4082c93b5db6fe07c089e7a601b05047, added full path resolution and join using path module.

### CODE REVIEW

**Comment by arthurvr** [comment]
Mind also adding a failing test?

**Comment by toszter** [comment]
@arthurvr --- Happy to. Mind providing an example of where and how? Here --> https://github.com/sindresorhus/grunt-php/blob/master/test/test.js?

**Comment by surfjedi** [comment]
We are having a similar issue but this fix with the branch isn't working. Getting this error:

Running "php:dev" (php) task
Warning: listener must be a function Use --force to continue.

**Comment by sindresorhus** [comment]
Closing for lack of tests.

**Comment by toszter** [comment]
I'd asked for an example of your desired tests... perhaps before closing, it would have been worth a little more effort?

**Pull request closed without merging**
