### PR TITLE
grunt-php does not work with node v0.10.x

### PR DESCRIPTION
**Pull request by thorsten**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Travis disagrees → https://travis-ci.org/sindresorhus/grunt-php/jobs/89385595

**Comment by thorsten** [comment]
Well, it's not working on our old environment here with node 0.10.12 on Windows 7, don't know if it's worth to investigate any further.

**Comment by sindresorhus** [comment]
Looking into Node.js 0.10 issues isn't very high on my priority list, but feel free to open an issue with some more information.

**Comment by thorsten** [comment]
Thanks, I'll check it more deeply.

**Pull request closed without merging**
